### PR TITLE
Adapt 0.61 design (context bar and theming)

### PR DESCRIPTION
**Pull request by mrsimpson**
With 0.61, Rocket.Chat releases the new context bar.
However, this needs some adaptation with respect to chatpal integration.

I moved the input statically to the left, but this is only a very quick fix.
cp moved left

Problems found:
- Selecting an item from the context bar does not make chatpal tab disappear
- Chatpal tab overlaps context tooltip
hidden
- Input needs to be aligned dynamically different on `home` and channels
cp home

### CODE REVIEW

**Comment by mrsimpson** [comment]
@tkurz you can checkout the assistify [0.61-branch](https://github.com/assistify/Rocket.Chat/tree/feature/0.61) in order to reproduce it easily

Btw: Of course I don't think that this "fix" is the proper solution. I basically wanted to point you to the fact that the UI has changed and that this has implications on the current implementation.

My suggestion for the first step is to basically re-use the existing search tab. Place the chatpal search dialog into the tab and display/hide it as any other normal tab.
This is not perfect from a UX perspective (since actually, the search is global and not related to the room), but until there's a proposal from Rocket.Chat how to design that, this is the easiest way

**Comment by mrsimpson** [comment]
@tkurz @vickyokrm I moved the search and its results fully to the tab bar. See the comment of https://github.com/redlink-gmbh/chatpal-search/pull/14/commits/3a22aae6a1f683145b54871539f6c197d243cc0d for details

**Comment by mrsimpson** [comment]
@tkurz this is how it currently looks like //cc @geekgonecrazy
demo-chatpal

**Comment by tkurz** [comment]
Hi @mrsimpson 
I like the video a lot, also the integration into the right side flex tab bar. There are only two smaller things. 1st) a direct search input on top would be amazing and 2nd) the search should appear already on the start screen (where the flex tab currently is not available). But this would need adaptions of rocket.chat. Nice work!

**Comment by mrsimpson** [comment]
@tkurz don't merge this yet - there's some substantial bug to be fixed:

The swapping of the search only works for the user who activates Chatpal.

**Pull request merged**
